apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskit-dpl
  labels:
    app: taskit
spec:
  replicas: {{ .Values.taskit.replicaCount | default 1 }}
  selector: 
    matchLabels:
      app: taskit
  template:
    metadata:
      labels:
        app: taskit
    spec:
      initContainers:
        - name: taskit-mgr
          image: {{ .Values.taskit.image }}
          args: ["-m", "flask", "db", "upgrade"]
          ports:
            - containerPort: {{ .Values.taskit.config.port | default 5000 }}
          envFrom:
            - configMapRef:
                name: taskit-conf
          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: taskit-secret
                  key: postgres-user-password
          resources:
            requests:
              memory: {{ .Values.taskit.resources.requests.memory }}
              cpu: {{ .Values.taskit.resources.requests.cpu }}
            limits:
              memory: {{ .Values.taskit.resources.limits.memory }}
              cpu: {{ .Values.taskit.resources.limits.cpu }}
      containers:
        - name: taskit
          image: {{ .Values.taskit.image }}
          ports:
            - containerPort: {{ .Values.taskit.config.port | default 5000 }}
          envFrom:
            - configMapRef:
                name: taskit-conf
          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: taskit-secret
                  key: postgres-user-password
          resources:
            requests:
              memory: {{ .Values.taskit.resources.requests.memory }}
              cpu: {{ .Values.taskit.resources.requests.cpu }}
            limits:
              memory: {{ .Values.taskit.resources.limits.memory }}
              cpu: {{ .Values.taskit.resources.limits.cpu }}
