apiVersion: v1
kind: Service
metadata:
  name: taskit-svc
  labels:
    app: taskit
spec:
{{ if .Values.taskit.ingress.enabled }}
  type: ClusterIP
{{ else }}
  type: {{ .Values.taskit.service.type | default "ClusterIP" }}
{{ end }}
  ports:
    - port: {{ .Values.taskit.service.port | default "80"}}
      targetPort: {{ .Values.taskit.config.port | default "5000"}}
  selector:
    app: taskit
