taskit:
  image: 644435390668.dkr.ecr.eu-central-1.amazonaws.com/taskit:1.0.1
  replicaCount: 3
  config:
    port: '5000'
  service:
    type: ClusterIP
    port: '80'
  ingress:
    enabled: true
    hostname: taskit.in
    ingressClassName: nginx
    tls:
      enabled: true
postgresql:
  auth:
    username: dbuser
    password: dbpass
    database: taskit
  architecture: standalone
  primary:
    name: primary
    resources:
      limits: {}
      requests:
        memory: 256Mi
        cpu: 250m
    persistence:
      enabled: true
      size: 8Gi
  service:
    type: ClusterIP
    ports:
      postgresql: 5432
