taskit:
  image: 644435390668.dkr.ecr.eu-central-1.amazonaws.com/taskit:1.1.0
  replicaCount: 3
  config:
    port: '5000'
    logLevel: DEBUG
  service:
    type: ClusterIP
    port: '80'
  ingress:
    enabled: true
    hostname: taskit.in
    ingressClassName: nginx
    tls:
      enabled: true
      staging: false
postgresql:
  auth:
    username: dbuser
    database: taskit
    existingSecret: taskit-secret
    secretKeys:
      userPasswordKey: postgres-user-password
      adminPasswordKey: postgres-admin-password
      replicationPasswordKey: postgres-repl-password
  architecture: standalone
  primary:
    name: primary
    resources:
      limits: {}
      requests:
        memory: 256Mi
        cpu: 250m
    persistence:
      enabled: true
      size: 8Gi
  service:
    type: ClusterIP
    ports:
      postgresql: 5432
