# App
taskit:
  image: 644435390668.dkr.ecr.eu-central-1.amazonaws.com/taskit:latest
  replicaCount: 3
  config:
    port: "5000"
  service:
    type: ClusterIP
    port: "80"
  ingress:
    # Enables the ingress resource - If true "service.type" is ignored and defaults to "ClusterIP"
    enabled: true
    hostname: taskit.in
    ingressClassName: nginx
    tls:
      enabled: true

# DB
postgresql:
  auth:
    username: "dbuser"
    password: "dbpass"
    database: "taskit"
  architecture: standalone
  primary:
    name: primary
    resources:
      limits: {}
      requests:
        memory: 256Mi
        cpu: 250m
    persistence:
      enabled: true
      size: 8Gi
  service:
    type: ClusterIP
    ports:
      postgresql: 5432
