apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-application
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://charts.jetstack.io
      targetRevision: 1.13.3
      chart: cert-manager
      helm:
        valueFiles:
          - "$mycharts/values/cert-manager-values.yml"
    - repoURL: git@github.com:yuval2313/taskit-gitops.git
      targetRevision: devops
      ref: mycharts
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
