apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx-application
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://kubernetes.github.io/ingress-nginx
      targetRevision: 4.9.0
      chart: ingress-nginx
      helm:
        valueFiles:
          - "$mycharts/values/ingress-nginx-values.yml"
    - repoURL: git@github.com:yuval2313/taskit-gitops.git
      targetRevision: devops
      ref: mycharts
  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-nginx
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
